package names

import "testing"

func TestDetectFrom(t *testing.T) {
	// Real first lines, because the detection is exactly a string match against
	// what each program writes and a paraphrase would prove nothing.
	cases := []struct {
		name string
		body string
		want manager
	}{{
		name: "systemd-resolved stub",
		body: "# This is /run/systemd/resolve/stub-resolv.conf managed by man:systemd-resolved(8).\n" +
			"nameserver 127.0.0.53\noptions edns0 trust-ad\n",
		want: mgrResolved,
	}, {
		name: "resolvconf",
		body: "# Generated by resolvconf\nnameserver 192.168.1.1\n",
		want: mgrResolvconf,
	}, {
		name: "NetworkManager",
		body: "# Generated by NetworkManager\nnameserver 192.168.1.1\n",
		want: mgrNetworkManager,
	}, {
		name: "hand-written",
		body: "nameserver 8.8.8.8\nnameserver 1.1.1.1\n",
		want: mgrPlain,
	}, {
		name: "empty",
		body: "",
		want: mgrPlain,
	}}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := detectFrom(tc.body); got != tc.want {
				t.Errorf("detectFrom = %v, want %v", got, tc.want)
			}
		})
	}
}

func TestOnlySystemdResolvedRoutesADomainByItself(t *testing.T) {
	// The consequence that matters: on anything but systemd-resolved, routing a
	// single domain needs dnsmasq, and without it apex names via the hosts file
	// are all this machine can have. Getting this backwards would have doze
	// quietly taking over resolution for everything.
	for _, m := range []manager{mgrResolvconf, mgrNetworkManager, mgrPlain, mgrUnknown} {
		if m == mgrResolved {
			continue
		}
		if canRouteDomain(m, false) {
			t.Errorf("%v claims it can route a domain with no dnsmasq present", m)
		}
		if !canRouteDomain(m, true) {
			t.Errorf("%v should be able to route a domain once dnsmasq is there", m)
		}
	}
	if !canRouteDomain(mgrResolved, false) {
		t.Error("systemd-resolved should be able to route a domain on its own")
	}
}

func TestManagerNames(t *testing.T) {
	// These strings are printed to users in the setup report.
	for m, want := range map[manager]string{
		mgrResolved:       "systemd-resolved",
		mgrResolvconf:     "resolvconf",
		mgrNetworkManager: "NetworkManager",
		mgrPlain:          "plain /etc/resolv.conf",
		mgrUnknown:        "unknown",
	} {
		if got := m.String(); got != want {
			t.Errorf("String() = %q, want %q", got, want)
		}
	}
}
