package names

// Which program owns /etc/resolv.conf, decided by the marker comment it writes
// there rather than by probing what is running.
//
// That distinction is the one Tailscale arrived at the hard way: a machine can
// have systemd-resolved running while something else entirely owns resolution,
// and asking the process table says the wrong thing. The file says who is
// actually in charge, because whoever is in charge signs it.
//
// This lives outside setup_linux.go so it can be tested anywhere — it is the
// piece most likely to be wrong, and a Linux build tag would mean it was never
// exercised on a Mac.

import "strings"

// manager is the thing that owns /etc/resolv.conf.
type manager int

const (
	mgrUnknown manager = iota
	mgrResolved
	mgrResolvconf
	mgrNetworkManager
	mgrPlain
)

func (m manager) String() string {
	switch m {
	case mgrResolved:
		return "systemd-resolved"
	case mgrResolvconf:
		return "resolvconf"
	case mgrNetworkManager:
		return "NetworkManager"
	case mgrPlain:
		return "plain /etc/resolv.conf"
	}
	return "unknown"
}

// canRouteDomain reports whether this machine can send one domain to our
// resolver without doze becoming the resolver for everything else.
//
// systemd-resolved does it natively. Otherwise it takes dnsmasq: plain
// NetworkManager cannot route by domain, and neither can a bare resolv.conf,
// so those machines get apex names from the hosts file and nothing more.
// detectFrom classifies the contents of a resolv.conf.
func detectFrom(s string) manager {
	switch {
	case strings.Contains(s, "systemd-resolved"), strings.Contains(s, "stub-resolv.conf"):
		return mgrResolved
	case strings.Contains(s, "Generated by resolvconf"):
		return mgrResolvconf
	case strings.Contains(s, "Generated by NetworkManager"):
		return mgrNetworkManager
	}
	return mgrPlain
}

// canRouteDomain reports whether this machine can send one domain to our
// resolver without doze becoming the resolver for everything else.
//
// systemd-resolved does it natively. Otherwise it takes dnsmasq: plain
// NetworkManager cannot route by domain, and neither can a bare resolv.conf,
// so those machines get apex names from the hosts file and nothing more.
//
// hasDnsmasq is passed rather than probed so the decision is a pure function of
// what was found — the caller does the looking.
func canRouteDomain(m manager, hasDnsmasq bool) bool {
	return m == mgrResolved || hasDnsmasq
}
